### ISSUE TITLE
Sodium incompatibility

### ISSUE THREAD

**Issue by TheSpiderDungeon** [miyucomics/sparkle#1]
Went through every mod in my list until I got to this one. Disabling it let the game launch, and enabling it threw an error through Sodium.

**Comment by miyucomics** [comment]
I haven't tested it with Sodium yet. Please send me the error and I'll have a fixed version out hopefully soon. In addition, I also want to know what version of the game you're using.

**Comment by TheSpiderDungeon** [comment]
Running 1.18.2
Sodium 0.4.1+build.15
Sparkle 1.0.0

Tried using Indium thinking it's the FRAPI issue, but no luck.

**Comment by miyucomics** [comment]
Is there a crash log or anything?

**Comment by TheSpiderDungeon** [comment]
https://paste.ee/p/Qf7QQ

**Comment by TheSpiderDungeon** [comment]
[crash-2022-04-24_23.12.10-client.txt](https://github.com/BrianComics/Sparkle/files/8551142/crash-2022-04-24_23.12.10-client.txt)

**Comment by miyucomics** [comment]
I found the error. Turns out, I'm using a class that no longer exists in 1.18.2 but does in previous versions so it has trouble loading it. I'll fix it tomorrow since it's nighttime for me right now. Thank you for bringing this to my attention! I'll close the issue once I fix it.

**Comment by superloach** [comment]
Hey there, just encountered this error myself. Any updates?

**Comment by miyucomics** [comment]
Oh, I just completely forgot about this! I'll get to fixing it. Sorry for the one month wait.
