### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [miyucomics/sparkle#3]
Hello, is it maybe possible to design the mod that players without the mod can still connect to a server?
My friend via GeyserMC can play without any problems on the server with this mod installed. I was managing my mods and deactivated Sparkle! and saw that I need it to connect to the server.
Greetings.

**Comment by miyucomics** [comment]
I don't think that is possible. I am sorry but I am not sure how servers work so I don't know how to prevent this problem. Perhaps you can ask your friend to remove the mod from the server?
