### ISSUE TITLE
Is it possible to add mods item?

### ISSUE THREAD

**Issue by MbtMarco** [miyucomics/sparkle#6]
I would like to add other blocks and items to work with Sparkle (From other mods)

**Comment by miyucomics** [comment]
Using a datapack, you can add any blocks or items to the #sparkly tag, including modded ones. You just need to type the identifier into a list and save it at `data/sparkle/tags/blocks/sparkly.json` or `data/sparkle/tags/items/sparkly.json` for blocks and items respectively.

For example, the following will make dirt sparkle.
```json
{
	"replace": false,
	"values": [
		"minecraft:dirt"
	]
}
```

**Comment by MbtMarco** [comment]
Ty :D
