### ISSUE TITLE
disable some sparkle effects

### ISSUE THREAD

**Issue by TheDinoKingK** [miyucomics/sparkle#8]
could there be a config to disable some sparkle effects, like the armor sparkle? or is there already something like that and I just don't know how to?

**Comment by miyucomics** [comment]
Currently there is no way to remove just the effect when wearing armor but you can remove the armor items from the item tag. I'll look into adding a way to disable specific effects.

**Comment by TheDinoKingK** [comment]
how do I do that?

**Comment by miyucomics** [comment]
You can use a datapack and replace the current item tag with a new one that doesn't include armor.
